// This file is auto-generated by Prisma
import { PrismaClient } from "@prisma/client"

// Singleton pattern with lazy initialization
let client: PrismaClient | undefined

function getPrismaClient(): PrismaClient {
  if (!client) {
    client = new PrismaClient()
  }
  return client
}

// Export a proxy that initializes on first use
export const prisma = new Proxy({} as PrismaClient, {
  get(target, prop) {
    return getPrismaClient()[prop as keyof PrismaClient]
  },
})
